# Generated by Django 3.2.6 on 2021-09-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_main_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='main_language',
            field=models.CharField(choices=[('ko', 'Korean'), ('en', 'English')], max_length=3, verbose_name='Main Language'),
        ),
    ]
