# Generated by Django 3.2.6 on 2021-10-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='goal',
            field=models.CharField(choices=[('conv', 'Conversation'), ('test', 'Test')], default='conv', max_length=4, verbose_name='Goal'),
        ),
    ]
