# Generated by Django 3.2.6 on 2021-10-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211003_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='main_language',
            field=models.CharField(choices=[('ko', 'Korean'), ('en', 'English')], default='ko', max_length=3, verbose_name='Main Language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='study_language',
            field=models.CharField(choices=[('ko', 'Korean'), ('en', 'English')], default='en', max_length=3, verbose_name='Study Language'),
        ),
    ]
