# Generated by Django 3.2.6 on 2021-10-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='study_language',
        ),
        migrations.AlterField(
            model_name='user',
            name='main_language',
            field=models.CharField(choices=[('ko', 'Korean'), ('en', 'English')], default='ko', max_length=3, verbose_name='Main Language'),
        ),
    ]
