# Generated by Django 3.2.6 on 2021-10-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20211008_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='study_language',
            field=models.CharField(choices=[('ko', 'Korean'), ('en', 'English')], default='en', max_length=3, verbose_name='Study Language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='goal',
            field=models.CharField(choices=[('conv', 'Conversation'), ('test', 'Test')], default='conv', max_length=4, verbose_name='Goal'),
        ),
    ]
